const fs = require('fs');
const path = require('path');

const sequenceDir = path.join(__dirname, '../public/sequence 2');
const outputFile = path.join(__dirname, '../lib/frames2.ts');

fs.readdir(sequenceDir, (err, files) => {
    if (err) {
        console.error('Error reading directory:', err);
        return;
    }

    const imageFiles = files.filter(file => file.endsWith('.webp')).sort();

    // Sort numerically if possible to ensure frame_0, frame_1 order
    // The default sort might do frame_1, frame_10, frame_100, frame_2...
    // Let's implement a better sort
    imageFiles.sort((a, b) => {
        const numA = parseInt(a.match(/frame_(\d+)/)[1]);
        const numB = parseInt(b.match(/frame_(\d+)/)[1]);
        return numA - numB;
    });

    const content = `// Generated by scripts/generate-frames.js
export const frames2 = [
${imageFiles.map(file => `    "/sequence 2/${file}",`).join('\n')}
];
`;

    fs.writeFile(outputFile, content, (err) => {
        if (err) {
            console.error('Error writing file:', err);
        } else {
            console.log('Successfully generated lib/frames2.ts with ' + imageFiles.length + ' frames.');
        }
    });
});
